export enum VerificationStatus {
  REJECTED = 'VERIFICATION_STATUS_REJECTED',
  PENDING = 'VERIFICATION_STATUS_PENDING',
  VERIFIED = 'VERIFICATION_STATUS_VERIFIED',
  UNVERIFIED = 'VERIFICATION_STATUS_UNVERIFIED',
  VERIFIED_REGISTERED_BEFORE_MARCH = 'VERIFICATION_STATUS_VERIFIED_REGISTERED_BEFORE_MARCH',
  UNVERIFIED_REGISTERED_AFTER_JANUARY = 'VERIFICATION_STATUS_UNVERIFIED_REGISTERED_AFTER_JANUARY'
}

export const MarchFirst = 1614542400000;

export const JanuaryFirst2022 = 1640995200000;
